# Generated by Django 4.2.7 on 2023-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_comment_remove_postimage_postid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postImages'),
        ),
    ]
