# Generated by Django 4.2.7 on 2023-11-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_post_lat_post_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='Posts.comment'),
            preserve_default=False,
        ),
    ]
