# Generated by Django 4.2.7 on 2023-11-24 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_remove_post_commments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='Posts.comment'),
        ),
    ]
