# Generated by Django 4.2.7 on 2023-11-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0011_post_commments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commments',
        ),
    ]
