# Generated by Django 4.2.7 on 2023-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_remove_post_commments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locURL',
            field=models.TextField(default=''),
        ),
    ]
